/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface BaseRevenueOSInterface extends Interface {
    getFunction(nameOrSignature: "adminWithdraw" | "buyLink" | "buyResale" | "createLink" | "creatorBalances" | "creatorLinks" | "getLinksByCreator" | "hasPurchased" | "nextLinkId" | "owner" | "paidLinks" | "platformFee" | "renounceOwnership" | "resalePrices" | "setPlatformFee" | "setResalePrice" | "transferOwnership" | "usdc" | "withdrawCreatorEarnings"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "LinkCreated" | "LinkPurchased" | "OwnershipTransferred" | "Withdraw"): EventFragment;

    encodeFunctionData(functionFragment: 'adminWithdraw', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'buyLink', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'buyResale', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'createLink', values: [BigNumberish, string, string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'creatorBalances', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'creatorLinks', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getLinksByCreator', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'hasPurchased', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'nextLinkId', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'paidLinks', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'platformFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'resalePrices', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'setPlatformFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setResalePrice', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'usdc', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdrawCreatorEarnings', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'adminWithdraw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buyLink', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buyResale', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createLink', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'creatorBalances', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'creatorLinks', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLinksByCreator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasPurchased', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextLinkId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paidLinks', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'platformFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resalePrices', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPlatformFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setResalePrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawCreatorEarnings', data: BytesLike): Result;
  }

  
    export namespace LinkCreatedEvent {
      export type InputTuple = [linkId: BigNumberish, creator: AddressLike, price: BigNumberish, title: string];
      export type OutputTuple = [linkId: bigint, creator: string, price: bigint, title: string];
      export interface OutputObject {linkId: bigint, creator: string, price: bigint, title: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LinkPurchasedEvent {
      export type InputTuple = [linkId: BigNumberish, buyer: AddressLike, seller: AddressLike, amount: BigNumberish];
      export type OutputTuple = [linkId: bigint, buyer: string, seller: string, amount: bigint];
      export interface OutputObject {linkId: bigint, buyer: string, seller: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawEvent {
      export type InputTuple = [creator: AddressLike, amount: BigNumberish];
      export type OutputTuple = [creator: string, amount: bigint];
      export interface OutputObject {creator: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface BaseRevenueOS extends BaseContract {
    
    connect(runner?: ContractRunner | null): BaseRevenueOS;
    waitForDeployment(): Promise<this>;

    interface: BaseRevenueOSInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    adminWithdraw: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    buyLink: TypedContractMethod<
      [linkId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    buyResale: TypedContractMethod<
      [linkId: BigNumberish, seller: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    createLink: TypedContractMethod<
      [price: BigNumberish, title: string, contentHash: string, royalty: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    creatorBalances: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    creatorLinks: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getLinksByCreator: TypedContractMethod<
      [creator: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    hasPurchased: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    nextLinkId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    paidLinks: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, string, string, bigint, bigint, bigint] & {creator: string, price: bigint, title: string, contentHash: string, sold: bigint, totalEarned: bigint, royaltyPercent: bigint }],
      'view'
    >
    

    
    platformFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    resalePrices: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    setPlatformFee: TypedContractMethod<
      [newFee: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setResalePrice: TypedContractMethod<
      [linkId: BigNumberish, price: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    usdc: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    withdrawCreatorEarnings: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'adminWithdraw'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'buyLink'): TypedContractMethod<
      [linkId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'buyResale'): TypedContractMethod<
      [linkId: BigNumberish, seller: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createLink'): TypedContractMethod<
      [price: BigNumberish, title: string, contentHash: string, royalty: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'creatorBalances'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'creatorLinks'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getLinksByCreator'): TypedContractMethod<
      [creator: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'hasPurchased'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'nextLinkId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'paidLinks'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, string, string, bigint, bigint, bigint] & {creator: string, price: bigint, title: string, contentHash: string, sold: bigint, totalEarned: bigint, royaltyPercent: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'platformFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resalePrices'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'setPlatformFee'): TypedContractMethod<
      [newFee: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setResalePrice'): TypedContractMethod<
      [linkId: BigNumberish, price: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'usdc'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'withdrawCreatorEarnings'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'LinkCreated'): TypedContractEvent<LinkCreatedEvent.InputTuple, LinkCreatedEvent.OutputTuple, LinkCreatedEvent.OutputObject>;
getEvent(key: 'LinkPurchased'): TypedContractEvent<LinkPurchasedEvent.InputTuple, LinkPurchasedEvent.OutputTuple, LinkPurchasedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Withdraw'): TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;

    filters: {
      
      'LinkCreated(uint256,address,uint256,string)': TypedContractEvent<LinkCreatedEvent.InputTuple, LinkCreatedEvent.OutputTuple, LinkCreatedEvent.OutputObject>;
      LinkCreated: TypedContractEvent<LinkCreatedEvent.InputTuple, LinkCreatedEvent.OutputTuple, LinkCreatedEvent.OutputObject>;
    

      'LinkPurchased(uint256,address,address,uint256)': TypedContractEvent<LinkPurchasedEvent.InputTuple, LinkPurchasedEvent.OutputTuple, LinkPurchasedEvent.OutputObject>;
      LinkPurchased: TypedContractEvent<LinkPurchasedEvent.InputTuple, LinkPurchasedEvent.OutputTuple, LinkPurchasedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Withdraw(address,uint256)': TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
      Withdraw: TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
    
    };
  }