/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BaseRevenueOS } from './BaseRevenueOS.js';
export * as factories from './factories/index.js';
export { BaseRevenueOS__factory } from './factories/BaseRevenueOS__factory.js';